# Generated by Django 2.2.13 on 2020-10-16 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0032_salesteam_supports_quick_entry'),
        ('accounting', '0026_account_supports_quick_entry'),
        ('inventory', '0025_auto_20200927_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('show_in_navigation', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.InventoryItem')),
            ],
        ),
        migrations.CreateModel(
            name='WebSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_title', models.CharField(blank=True, default='', max_length=255)),
                ('promo_message', models.TextField(blank=True, default='')),
                ('show_banner', models.BooleanField(default=False)),
                ('banner_image', models.ImageField(upload_to='')),
                ('about_page_text', models.TextField()),
                ('about_page_image', models.ImageField(null=True, upload_to='')),
                ('shop_address', models.TextField()),
                ('shop_email', models.EmailField(max_length=254)),
                ('shop_telephone', models.CharField(max_length=254)),
                ('shop_alternate_telephone', models.CharField(blank=True, default='', max_length=254)),
                ('shop_gps', models.CharField(blank=True, default='', max_length=254)),
                ('default_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Currency')),
            ],
            options={
                'verbose_name_plural': 'WebSettings',
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(max_length=64)),
                ('attribute', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.InventoryItem')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.InventoryItem')),
            ],
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.FaqCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Department')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Category')),
            ],
            options={
                'verbose_name_plural': 'Web Categories',
            },
        ),
    ]
