# Generated by Django 2.2.13 on 2020-10-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'verbose_name_plural': 'FAQ Categories'},
        ),
        migrations.AlterModelOptions(
            name='faqitem',
            options={'verbose_name_plural': 'FAQ Items'},
        ),
        migrations.AlterModelOptions(
            name='sku',
            options={'verbose_name_plural': 'SKU'},
        ),
        migrations.AlterModelOptions(
            name='websettings',
            options={'verbose_name_plural': 'Website Settings'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'verbose_name_plural': 'Wishlist Items'},
        ),
    ]
