# Generated by Django 2.2.10 on 2020-10-20 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_account_supports_quick_entry'),
        ('inventory', '0025_auto_20200927_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomponent',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='equipment_component',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='product_component',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='unit_purchase_price',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='asset_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Asset'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='condition',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('poor', 'Poor'), ('broken', 'Not Functioning')], default='excellent', max_length=16),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='tax',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounting.Tax'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Product'), (1, 'Equipment'), (2, 'Consumables')]),
        ),
        migrations.DeleteModel(
            name='EquipmentComponent',
        ),
        migrations.DeleteModel(
            name='ProductComponent',
        ),
    ]
