# Generated by Django 2.2.13 on 2020-10-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20201020_2045'),
        ('inventory', '0026_inventoryitem_featured'),
    ]

    operations = [
    ]
