# Generated by Django 2.2.10 on 2020-10-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0033_auto_20201020_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
