# Generated by Django 2.2.10 on 2020-10-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0034_auto_20201020_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
